/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuelRouteImport } from './routes/fuel.tsx'
import { Route as Rec90RouteImport } from './routes/Rec_90.tsx'
import { Route as DieselFuelRouteImport } from './routes/DieselFuel.tsx'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const HomeRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)

const Rec90Route = Rec90RouteImport.update({
  id: '/Rec90',
  path: '/Rec90',
  getParentRoute: () => rootRouteImport,
} as any)

const DieselFuelRoute = DieselFuelRouteImport.update({
  id: '/rec90-1',
  path: '/rec90-1',
  getParentRoute: () => rootRouteImport,
} as any)


export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/fuel': typeof HomeRoute
  '/rec90-1': typeof DieselFuelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/fuel': typeof HomeRoute
  '/rec90-1': typeof DieselFuelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/fuel': typeof HomeRoute
  '/Rec90': typeof Rec90Route
   '/rec90-1': typeof DieselFuelRoute

}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/products' | '/services'| '/fuel' | '/Rec90'| '/rec90-1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/products' | '/services' | '/fuel' | '/Rec90' | '/rec90-1'
  id: '__root__' | '/' | '/about' | '/contact' | '/products' | '/services' | '/fuel' | '/Rec90' | '/rec90-1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRoute
  HomeRoute: typeof HomeRoute
  Rec90Route: typeof Rec90Route
  DieselFuelRoute: typeof DieselFuelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
     '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Rec90': {
      id: '/Rec90'
      path: '/Rec90'
      fullPath: '/Rec90'
      preLoaderRoute: typeof Rec90RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec90-1': {
      id: '/rec90-1'
      path: '/rec90-1'
      fullPath: '/rec90-1'
      preLoaderRoute: typeof DieselFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  HomeRoute: HomeRoute,
  Rec90Route: Rec90Route,
  DieselFuelRoute: DieselFuelRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
